# Kernel config
TARGET_KERNEL_CONFIG += vendor/zijin_QGKI.config

# Kernel modules
BOARD_VENDOR_KERNEL_MODULES_LOAD += goodix_core.ko
BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD += goodix_core.ko
BOOT_KERNEL_MODULES += $(BOARD_VENDOR_RAMDISK_RECOVERY_KERNEL_MODULES_LOAD)
